---
swagger: "2.0"
info:
  description: "The currency APIs help you retrieve exchange rates and convert prices\
    \ between currencies easily."
  version: "v1"
  title: "currencyapi"
host: "api.cloudmersive.com"
schemes:
- "https"
paths:
  /currency/exchange-rates/list-available:
    post:
      tags:
      - "CurrencyExchange"
      summary: "Get a list of available currencies and corresponding countries"
      description: "Enumerates available currencies and the countries that correspond\
        \ to these currencies."
      operationId: "CurrencyExchange_GetAvailableCurrencies"
      consumes: []
      produces:
      - "application/json"
      - "text/json"
      - "application/xml"
      - "text/xml"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/AvailableCurrencyResponse"
      security:
      - Apikey: []
  /currency/exchange-rates/convert/{source}/to/{destination}:
    post:
      tags:
      - "CurrencyExchange"
      summary: "Converts a price from the source currency into the destination currency"
      description: "Automatically converts the price in the source currency into the\
        \ destination currency using the latest available currency exchange rate data."
      operationId: "CurrencyExchange_ConvertCurrency"
      consumes:
      - "application/json"
      - "text/json"
      produces:
      - "application/json"
      - "text/json"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "source"
        in: "path"
        description: "Source currency three-digit code (ISO 4217), e.g. USD, EUR,\
          \ etc."
        required: true
        type: "string"
        x-exportParamName: "Source"
      - name: "destination"
        in: "path"
        description: "Destination currency three-digit code (ISO 4217), e.g. USD,\
          \ EUR, etc."
        required: true
        type: "string"
        x-exportParamName: "Destination"
      - in: "body"
        name: "sourcePrice"
        description: "Input price, such as 19.99 in source currency"
        required: true
        schema:
          type: "number"
          format: "double"
        x-exportParamName: "SourcePrice"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ConvertedCurrencyResult"
      security:
      - Apikey: []
  /currency/exchange-rates/get/{source}/to/{destination}:
    post:
      tags:
      - "CurrencyExchange"
      summary: "Gets the exchange rate from the source currency into the destination\
        \ currency"
      description: "Automatically gets the exchange rate from the source currency\
        \ into the destination currency using the latest available currency exchange\
        \ rate data."
      operationId: "CurrencyExchange_GetExchangeRate"
      consumes: []
      produces:
      - "application/json"
      - "text/json"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "source"
        in: "path"
        description: "Source currency three-digit code (ISO 4217), e.g. USD, EUR,\
          \ etc."
        required: true
        type: "string"
        x-exportParamName: "Source"
      - name: "destination"
        in: "path"
        description: "Destination currency three-digit code (ISO 4217), e.g. USD,\
          \ EUR, etc."
        required: true
        type: "string"
        x-exportParamName: "Destination"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ExchangeRateResult"
      security:
      - Apikey: []
securityDefinitions:
  Apikey:
    description: "API Key Authentication"
    type: "apiKey"
    name: "Apikey"
    in: "header"
definitions:
  AvailableCurrencyResponse:
    type: "object"
    properties:
      Currencies:
        type: "array"
        description: "List of available currencies from the API"
        items:
          $ref: "#/definitions/AvailableCurrency"
    description: "Result of performing an enumerate currencies operation"
    example:
      Currencies:
      - CountryThreeLetterCode: "CountryThreeLetterCode"
        ISOCurrencyCode: "ISOCurrencyCode"
        CountryName: "CountryName"
        CurrencyEnglishName: "CurrencyEnglishName"
        CurrencySymbol: "CurrencySymbol"
        IsEuropeanUnionMember: true
        CountryISOTwoLetterCode: "CountryISOTwoLetterCode"
      - CountryThreeLetterCode: "CountryThreeLetterCode"
        ISOCurrencyCode: "ISOCurrencyCode"
        CountryName: "CountryName"
        CurrencyEnglishName: "CurrencyEnglishName"
        CurrencySymbol: "CurrencySymbol"
        IsEuropeanUnionMember: true
        CountryISOTwoLetterCode: "CountryISOTwoLetterCode"
  AvailableCurrency:
    type: "object"
    properties:
      ISOCurrencyCode:
        type: "string"
        description: "ISO 4217 currency three-letter code associated with the country"
      CurrencySymbol:
        type: "string"
        description: "Symbol associated with the currency"
      CurrencyEnglishName:
        type: "string"
        description: "Full name of the currency"
      CountryName:
        type: "string"
        description: "Name of the country"
      CountryThreeLetterCode:
        type: "string"
        description: "Three-letter ISO 3166-1 country code"
      CountryISOTwoLetterCode:
        type: "string"
        description: "Two-letter ISO 3166-1 country code"
      IsEuropeanUnionMember:
        type: "boolean"
        description: "True if this country is currently a member of the European Union\
          \ (EU), false otherwise"
    description: "Details of a specific currency"
    example:
      CountryThreeLetterCode: "CountryThreeLetterCode"
      ISOCurrencyCode: "ISOCurrencyCode"
      CountryName: "CountryName"
      CurrencyEnglishName: "CurrencyEnglishName"
      CurrencySymbol: "CurrencySymbol"
      IsEuropeanUnionMember: true
      CountryISOTwoLetterCode: "CountryISOTwoLetterCode"
  ConvertedCurrencyResult:
    type: "object"
    properties:
      ConvertedPrice:
        type: "number"
        format: "double"
        description: "The converted price in the destination currency"
      ISOCurrencyCode:
        type: "string"
        description: "ISO 4217 currency three-letter code of destination price"
      CurrencySymbol:
        type: "string"
        description: "Destination currency symbol"
      FormattedPriceAsString:
        type: "string"
        description: "Formatted price in the destination currency as a string"
    description: "Result of performing a Convert Currency operation"
    example:
      FormattedPriceAsString: "FormattedPriceAsString"
      ISOCurrencyCode: "ISOCurrencyCode"
      ConvertedPrice: 0.8008281904610115
      CurrencySymbol: "CurrencySymbol"
  ExchangeRateResult:
    type: "object"
    properties:
      ExchangeRate:
        type: "number"
        format: "double"
        description: "The exchange rate from the source to the destination currency"
    description: "Result of performing a get exchange rate operation"
    example:
      ExchangeRate: 0.8008281904610115
